//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayZServerControllerUI.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class DayzCtrlSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DayzCtrlSettings defaultInstance = ((DayzCtrlSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DayzCtrlSettings())));
        
        public static DayzCtrlSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamCmdPath {
            get {
                return ((string)(this["SteamCmdPath"]));
            }
            set {
                this["SteamCmdPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\SharedFolder\\DayZServer\\Modlist.txt")]
        public string ModMappingFilePath {
            get {
                return ((string)(this["ModMappingFilePath"]));
            }
            set {
                this["ModMappingFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\SharedFolder\\DayZServer\\DayZServer_x64.exe")]
        public string DayzServerExePath {
            get {
                return ((string)(this["DayzServerExePath"]));
            }
            set {
                this["DayzServerExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\Program Files (x86)\\Steam\\steamapps\\common\\DayZ\\DayZ_x64.exe")]
        public string DayzGameExePath {
            get {
                return ((string)(this["DayzGameExePath"]));
            }
            set {
                this["DayzGameExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04:00:00")]
        public global::System.TimeSpan ServerRestartPeriod {
            get {
                return ((global::System.TimeSpan)(this["ServerRestartPeriod"]));
            }
            set {
                this["ServerRestartPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MuteDiscordBot {
            get {
                return ((bool)(this["MuteDiscordBot"]));
            }
            set {
                this["MuteDiscordBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSteamCmd {
            get {
                return ((bool)(this["UseSteamCmd"]));
            }
            set {
                this["UseSteamCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\SharedFolder\\discord.txt")]
        public string DiscordDataFilePath {
            get {
                return ((string)(this["DiscordDataFilePath"]));
            }
            set {
                this["DiscordDataFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteamCredentials2")]
        public string SteamCredentialStorageName {
            get {
                return ((string)(this["SteamCredentialStorageName"]));
            }
            set {
                this["SteamCredentialStorageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstStart {
            get {
                return ((bool)(this["FirstStart"]));
            }
            set {
                this["FirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\SharedFolder\\DayZServer\\Profiles\\server_console.log")]
        public string DayzServerLogFilePath {
            get {
                return ((string)(this["DayzServerLogFilePath"]));
            }
            set {
                this["DayzServerLogFilePath"] = value;
            }
        }
    }
}
